name: ✨ 機能リクエスト
description: 新機能の提案やアイデアを共有する
title: "[Feature]: "
labels: ["✨feature", "00.未着手"]
body:
  - type: markdown
    attributes:
      value: |
        ## 機能リクエスト

        AI Course Content Generatorへの機能追加のご提案、ありがとうございます！
        以下の情報をできる限り詳しく記入してください。

  - type: textarea
    id: problem
    attributes:
      label: 解決したい課題
      description: どのような課題や不便さを解決したいですか？
      placeholder: |
        例：現在、コース生成後に手動で各セクションのタイトルを編集する必要があり、時間がかかる
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 提案する機能
      description: どのような機能があれば課題が解決できますか？具体的に説明してください
      placeholder: |
        例：
        - コース生成時に「一括タイトル編集モード」を追加
        - CSVファイルからタイトル一覧をインポート
        - AIによる自動タイトル最適化機能
    validations:
      required: true

  - type: textarea
    id: benefits
    attributes:
      label: 期待される効果
      description: この機能が実装されると、どのようなメリットがありますか？
      placeholder: |
        例：
        - 編集時間が50%削減される
        - より一貫性のあるコースタイトルが作成できる
        - 大量コース作成時の効率が向上する
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 代替案
      description: 他に考えられる解決方法があれば記入してください
      placeholder: |
        例：
        - テンプレート機能の拡張
        - ショートカットキーの追加

  - type: dropdown
    id: category
    attributes:
      label: 機能カテゴリ
      description: この機能はどのカテゴリに該当しますか？
      options:
        - 🤖 AI機能（コース生成、最適化）
        - ✏️ 編集機能（エディタ、管理）
        - 📊 分析・レポート
        - 🎨 UI/UX改善
        - 🔐 セキュリティ・認証
        - 💰 課金・決済
        - 📱 モバイル対応
        - 🔗 外部連携（API、統合）
        - 📚 ドキュメント
        - その他
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: 優先度（ご自身の評価）
      description: あなたにとって、この機能の重要度は？
      options:
        - 🔥 非常に高い（日常的に必要）
        - ⭐ 高い（週に数回は必要）
        - ➡️ 中程度（月に数回は必要）
        - 🟢 低い（あれば便利）
        - ⬇️ 非常に低い（Nice to have）
    validations:
      required: true

  - type: dropdown
    id: users
    attributes:
      label: 対象ユーザー
      description: この機能は誰にとって有用ですか？
      options:
        - すべてのユーザー
        - 教育コンテンツ作成者
        - 企業研修担当者
        - 教育機関（学校、大学）
        - パートナー
        - 管理者
        - その他

  - type: textarea
    id: mockup
    attributes:
      label: モックアップ・参考画像
      description: イメージ図や参考となるUIのスクリーンショットがあれば添付してください
      placeholder: ここに画像をドラッグ&ドロップ

  - type: textarea
    id: reference
    attributes:
      label: 参考事例
      description: 他のサービスで同様の機能があれば紹介してください
      placeholder: |
        例：
        - Notion: ブロック単位での一括編集機能
        - Canva: テンプレートのカスタマイズ機能

  - type: dropdown
    id: willingness
    attributes:
      label: 実装への協力意向
      description: もし実装された場合、テストや フィードバックに協力いただけますか？
      options:
        - はい、積極的に協力したい
        - はい、可能な範囲で協力したい
        - 状況によって検討する
        - いいえ、利用のみ希望
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: 追加情報
      description: その他、伝えたい情報があれば記入してください

  - type: checkboxes
    id: terms
    attributes:
      label: 確認事項
      options:
        - label: 既存のIssueで同じ提案がないことを確認しました
          required: true
        - label: この機能が多くのユーザーに有益だと考えています
          required: true
